name: test
on:
	push:
		branches:
			- 'master'
jobs:
	test:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v2
			- name: Use Node.js
			  uses: actions/setup-node@v1
			  with:
			      node-version: 14
			-name: deloy
			 run: |
			     npm i
				 npx @dcloudio/uvm 3.2.0 --manager npm
				 npm run build:app
